// ============================================================
// Dữ liệu mẫu (Mock Data) cho giai đoạn phát triển UI
// Mô phỏng theo cấu trúc sản phẩm nội thất MOHO
// ============================================================

import { Product, Category, Banner, BlogPost } from '@/types';

// --- Danh mục sản phẩm ---
export const mockCategories: Category[] = [
  { id: 1, name: 'Sofa', slug: 'sofa', iconUrl: '/images/categories/sofa.svg', imageUrl: '/images/categories/sofa.jpg', sortOrder: 1, isActive: true },
  { id: 2, name: 'Giường ngủ', slug: 'giuong-ngu', iconUrl: '/images/categories/bed.svg', imageUrl: '/images/categories/bed.jpg', sortOrder: 2, isActive: true },
  { id: 3, name: 'Tủ quần áo', slug: 'tu-quan-ao', iconUrl: '/images/categories/wardrobe.svg', imageUrl: '/images/categories/wardrobe.jpg', sortOrder: 3, isActive: true },
  { id: 4, name: 'Bàn làm việc', slug: 'ban-lam-viec', iconUrl: '/images/categories/desk.svg', imageUrl: '/images/categories/desk.jpg', sortOrder: 4, isActive: true },
  { id: 5, name: 'Ghế', slug: 'ghe', iconUrl: '/images/categories/chair.svg', imageUrl: '/images/categories/chair.jpg', sortOrder: 5, isActive: true },
  { id: 6, name: 'Kệ sách', slug: 'ke-sach', iconUrl: '/images/categories/shelf.svg', imageUrl: '/images/categories/shelf.jpg', sortOrder: 6, isActive: true },
  { id: 7, name: 'Bàn ăn', slug: 'ban-an', iconUrl: '/images/categories/dining.svg', imageUrl: '/images/categories/dining.jpg', sortOrder: 7, isActive: true },
  { id: 8, name: 'Đồ trang trí', slug: 'do-trang-tri', iconUrl: '/images/categories/decor.svg', imageUrl: '/images/categories/decor.jpg', sortOrder: 8, isActive: true },
];

// --- Sản phẩm mẫu ---
export const mockProducts: Product[] = [
  {
    id: 1,
    name: 'Ghế Sofa 1m8 Nội Thất Xinh MOCHI',
    slug: 'ghe-sofa-1m8-noi-that-xinh-mochi',
    sku: 'NTXSF001',
    description: 'Ghế sofa cao cấp với thiết kế hiện đại, phong cách Bắc Âu. Bọc vải polyester chống nước, khung gỗ tự nhiên chắc chắn.',
    shortDescription: 'Sofa 1m8 phong cách Bắc Âu, bọc vải chống nước',
    price: 9990000,
    comparePrice: 13990000,
    categoryId: 1,
    material: 'Vải 100% polyester, chân gỗ cao su, khung gỗ tự nhiên',
    dimensions: 'W179 x D79 x H73 cm',
    weight: 45,
    soldCount: 24,
    isActive: true,
    isFeatured: true,
    seoTitle: 'Ghế Sofa 1m8 MOCHI - Nội Thất Xinh',
    seoDescription: 'Ghế sofa 1m8 phong cách Bắc Âu, bọc vải chống nước, khung gỗ tự nhiên.',
    images: [
      { id: 1, productId: 1, imageUrl: '/images/products/sofa-mochi-1.jpg', altText: 'Sofa MOCHI be', sortOrder: 1 },
      { id: 2, productId: 1, imageUrl: '/images/products/sofa-mochi-2.jpg', altText: 'Sofa MOCHI xanh', sortOrder: 2 },
    ],
    variants: [
      { id: 1, productId: 1, color: 'Be', colorHex: '#D4C5A9', size: '1m8', price: 9990000, stock: 15, sku: 'NTXSF001-BE' },
      { id: 2, productId: 1, color: 'Xanh rêu', colorHex: '#4A7C59', size: '1m8', price: 9990000, stock: 8, sku: 'NTXSF001-GR' },
    ],
    createdAt: '2024-01-15T08:00:00Z',
  },
  {
    id: 2,
    name: 'Ghế Armchair Thư Giãn Kèm Đôn OLLY',
    slug: 'ghe-armchair-thu-gian-kem-don-olly',
    sku: 'NTXCH002',
    description: 'Ghế armchair thư giãn với đệm dày, kèm đôn để chân. Thiết kế tinh tế, phù hợp không gian phòng khách hiện đại.',
    shortDescription: 'Armchair kèm đôn, đệm dày êm ái',
    price: 10990000,
    comparePrice: 18480000,
    categoryId: 5,
    material: 'Vải bọc cao cấp, nệm mút siêu đàn hồi, khung thép',
    dimensions: 'W85 x D90 x H95 cm',
    weight: 35,
    soldCount: 56,
    isActive: true,
    isFeatured: true,
    seoTitle: 'Ghế Armchair OLLY - Nội Thất Xinh',
    seoDescription: 'Ghế armchair thư giãn kèm đôn để chân OLLY, thiết kế phong cách Bắc Âu.',
    images: [
      { id: 3, productId: 2, imageUrl: '/images/products/armchair-olly-1.jpg', altText: 'Armchair OLLY xanh', sortOrder: 1 },
    ],
    variants: [
      { id: 3, productId: 2, color: 'Xanh rêu', colorHex: '#4A7C59', size: 'Standard', price: 10990000, stock: 12, sku: 'NTXCH002-GR' },
      { id: 4, productId: 2, color: 'Kem', colorHex: '#F5E6CC', size: 'Standard', price: 10990000, stock: 5, sku: 'NTXCH002-CR' },
    ],
    createdAt: '2024-02-10T08:00:00Z',
  },
  {
    id: 3,
    name: 'Giường Ngủ Bọc Vải Phong Cách Ý COMET',
    slug: 'giuong-ngu-boc-vai-phong-cach-y-comet',
    sku: 'NTXBD003',
    description: 'Giường ngủ bọc vải cao cấp phong cách Ý, đầu giường êm ái. Phù hợp phòng ngủ hiện đại, thanh lịch.',
    shortDescription: 'Giường bọc vải phong cách Ý, đầu giường êm',
    price: 14490000,
    comparePrice: 16990000,
    categoryId: 2,
    material: 'Vải bọc nhung, gỗ MDF lõi xanh chống ẩm, sắt gia cường',
    dimensions: 'W180 x D200 x H100 cm',
    weight: 85,
    soldCount: 0,
    isActive: true,
    isFeatured: true,
    seoTitle: 'Giường Ngủ Bọc Vải COMET - Nội Thất Xinh',
    seoDescription: 'Giường ngủ bọc vải phong cách Ý COMET, đầu giường êm ái, thanh lịch.',
    images: [
      { id: 4, productId: 3, imageUrl: '/images/products/bed-comet-1.jpg', altText: 'Giường COMET', sortOrder: 1 },
    ],
    variants: [
      { id: 5, productId: 3, color: 'Xám', colorHex: '#9E9E9E', size: '1m8', price: 14490000, stock: 7, sku: 'NTXBD003-GY' },
    ],
    createdAt: '2024-03-05T08:00:00Z',
  },
  {
    id: 4,
    name: 'Giường Ngủ Bọc Da Cao Cấp Hiện Đại BLINK',
    slug: 'giuong-ngu-boc-da-cao-cap-hien-dai-blink',
    sku: 'NTXBD004',
    description: 'Giường ngủ bọc da cao cấp với thiết kế hiện đại, đầu giường bọc da mềm mại. Khung gỗ tự nhiên bền chắc.',
    shortDescription: 'Giường bọc da cao cấp, thiết kế hiện đại',
    price: 15990000,
    comparePrice: 17490000,
    categoryId: 2,
    material: 'Da PU cao cấp, gỗ MDF lõi xanh, sắt gia cường',
    dimensions: 'W180 x D200 x H105 cm',
    weight: 90,
    soldCount: 8,
    isActive: true,
    isFeatured: false,
    seoTitle: 'Giường Ngủ Bọc Da BLINK - Nội Thất Xinh',
    seoDescription: 'Giường ngủ bọc da cao cấp BLINK thiết kế hiện đại.',
    images: [
      { id: 5, productId: 4, imageUrl: '/images/products/bed-blink-1.jpg', altText: 'Giường BLINK', sortOrder: 1 },
    ],
    variants: [
      { id: 6, productId: 4, color: 'Nâu đậm', colorHex: '#5D4037', size: '1m8', price: 15990000, stock: 3, sku: 'NTXBD004-BR' },
    ],
    createdAt: '2024-03-20T08:00:00Z',
  },
  {
    id: 5,
    name: 'Combo Tủ Quần Áo Cánh Kính ASTRO',
    slug: 'combo-tu-quan-ao-canh-kinh-astro',
    sku: 'NTXWR005',
    description: 'Combo tủ quần áo cánh kính hiện đại, nhiều kích thước tùy chọn. Thiết kế tối giản, tối ưu không gian lưu trữ.',
    shortDescription: 'Tủ quần áo cánh kính, nhiều kích thước',
    price: 23490000,
    comparePrice: 27480000,
    categoryId: 3,
    material: 'Gỗ MDF phủ melamine, kính cường lực, ray trượt giảm chấn',
    dimensions: 'W240 x D60 x H220 cm',
    weight: 150,
    soldCount: 15,
    isActive: true,
    isFeatured: true,
    seoTitle: 'Combo Tủ Quần Áo ASTRO - Nội Thất Xinh',
    seoDescription: 'Combo tủ quần áo cánh kính ASTRO, thiết kế hiện đại, nhiều kích thước.',
    images: [
      { id: 6, productId: 5, imageUrl: '/images/products/wardrobe-astro-1.jpg', altText: 'Tủ ASTRO', sortOrder: 1 },
    ],
    variants: [
      { id: 7, productId: 5, color: 'Gỗ sáng', colorHex: '#D4A574', size: '2m4', price: 23490000, stock: 4, sku: 'NTXWR005-LW' },
    ],
    createdAt: '2024-04-01T08:00:00Z',
  },
  {
    id: 6,
    name: 'Tủ Quần Áo Cánh Kính 60cm ASTRO - Tủ Đơn',
    slug: 'tu-quan-ao-canh-kinh-60cm-astro-tu-don',
    sku: 'NTXWR006',
    description: 'Tủ quần áo đơn cánh kính 60cm, nhỏ gọn phù hợp phòng nhỏ hoặc bổ sung thêm.',
    shortDescription: 'Tủ đơn cánh kính 60cm nhỏ gọn',
    price: 9490000,
    comparePrice: 10490000,
    categoryId: 3,
    material: 'Gỗ MDF phủ melamine, kính cường lực',
    dimensions: 'W60 x D60 x H220 cm',
    weight: 55,
    soldCount: 32,
    isActive: true,
    isFeatured: false,
    seoTitle: 'Tủ Quần Áo 60cm ASTRO Đơn - Nội Thất Xinh',
    seoDescription: 'Tủ quần áo cánh kính đơn 60cm ASTRO, nhỏ gọn tiện lợi.',
    images: [
      { id: 7, productId: 6, imageUrl: '/images/products/wardrobe-astro-single-1.jpg', altText: 'Tủ ASTRO đơn', sortOrder: 1 },
    ],
    variants: [
      { id: 8, productId: 6, color: 'Gỗ sáng', colorHex: '#D4A574', size: '60cm', price: 9490000, stock: 10, sku: 'NTXWR006-LW' },
    ],
    createdAt: '2024-04-10T08:00:00Z',
  },
  {
    id: 7,
    name: 'Giường Ngủ Bọc Vải Cao Cấp BOND',
    slug: 'giuong-ngu-boc-vai-cao-cap-bond',
    sku: 'NTXBD007',
    description: 'Giường ngủ bọc vải cao cấp BOND với thiết kế sang trọng, đầu giường vải bouclé thời thượng.',
    shortDescription: 'Giường bọc vải bouclé cao cấp BOND',
    price: 14990000,
    comparePrice: 17490000,
    categoryId: 2,
    material: 'Vải bouclé, gỗ MDF lõi xanh, sắt gia cường',
    dimensions: 'W180 x D200 x H110 cm',
    weight: 88,
    soldCount: 41,
    isActive: true,
    isFeatured: true,
    seoTitle: 'Giường Ngủ Bọc Vải BOND - Nội Thất Xinh',
    seoDescription: 'Giường ngủ bọc vải cao cấp BOND, thiết kế sang trọng.',
    images: [
      { id: 8, productId: 7, imageUrl: '/images/products/bed-bond-1.jpg', altText: 'Giường BOND', sortOrder: 1 },
    ],
    variants: [
      { id: 9, productId: 7, color: 'Kem', colorHex: '#F5E6CC', size: '1m8', price: 14990000, stock: 6, sku: 'NTXBD007-CR' },
    ],
    createdAt: '2024-04-15T08:00:00Z',
  },
  {
    id: 8,
    name: 'Bàn Làm Việc Gỗ Tự Nhiên VIENNA',
    slug: 'ban-lam-viec-go-tu-nhien-vienna',
    sku: 'NTXDK008',
    description: 'Bàn làm việc gỗ tự nhiên VIENNA, thiết kế tối giản kiểu Scandinavian. Mặt bàn rộng, có ngăn kéo lưu trữ.',
    shortDescription: 'Bàn làm việc gỗ tự nhiên Scandinavian',
    price: 5990000,
    comparePrice: 7490000,
    categoryId: 4,
    material: 'Gỗ cao su tự nhiên, sơn PU chống trầy',
    dimensions: 'W120 x D60 x H75 cm',
    weight: 28,
    soldCount: 67,
    isActive: true,
    isFeatured: true,
    seoTitle: 'Bàn Làm Việc VIENNA - Nội Thất Xinh',
    seoDescription: 'Bàn làm việc gỗ tự nhiên VIENNA, phong cách Scandinavian.',
    images: [
      { id: 9, productId: 8, imageUrl: '/images/products/desk-vienna-1.jpg', altText: 'Bàn VIENNA', sortOrder: 1 },
    ],
    variants: [
      { id: 10, productId: 8, color: 'Gỗ tự nhiên', colorHex: '#C19A6B', size: '1m2', price: 5990000, stock: 20, sku: 'NTXDK008-NW' },
    ],
    createdAt: '2024-05-01T08:00:00Z',
  },
];

// --- Banner trang chủ ---
export const mockBanners: Banner[] = [
  {
    id: 1,
    title: 'Bộ Sưu Tập Mùa Hè 2024',
    subtitle: 'Giảm đến 40% cho toàn bộ sofa',
    imageUrl: '/images/banners/banner-1.jpg',
    linkUrl: '/products?category=sofa',
    sortOrder: 1,
    isActive: true,
  },
  {
    id: 2,
    title: 'Phòng Ngủ Hoàn Hảo',
    subtitle: 'Khám phá bộ sưu tập giường ngủ mới',
    imageUrl: '/images/banners/banner-2.jpg',
    linkUrl: '/products?category=giuong-ngu',
    sortOrder: 2,
    isActive: true,
  },
  {
    id: 3,
    title: 'Thiết Kế Nội Thất',
    subtitle: 'Dịch vụ thiết kế & thi công trọn gói',
    imageUrl: '/images/banners/banner-3.jpg',
    linkUrl: '/thiet-ke-thi-cong',
    sortOrder: 3,
    isActive: true,
  },
];

// --- Blog mẫu ---
export const mockBlogPosts: BlogPost[] = [
  {
    id: 1,
    title: '10 Xu hướng nội thất phòng khách 2024',
    slug: '10-xu-huong-noi-that-phong-khach-2024',
    excerpt: 'Khám phá những xu hướng nội thất phòng khách hot nhất năm 2024 với phong cách tối giản, hiện đại.',
    content: '',
    thumbnailUrl: '/images/blog/blog-1.jpg',
    authorName: 'Nội Thất Xinh',
    createdAt: '2024-06-01T08:00:00Z',
  },
  {
    id: 2,
    title: 'Cách chọn sofa phù hợp cho căn hộ nhỏ',
    slug: 'cach-chon-sofa-phu-hop-can-ho-nho',
    excerpt: 'Hướng dẫn chọn sofa phù hợp với không gian nhỏ, tối ưu công năng sử dụng.',
    content: '',
    thumbnailUrl: '/images/blog/blog-2.jpg',
    authorName: 'Nội Thất Xinh',
    createdAt: '2024-05-20T08:00:00Z',
  },
  {
    id: 3,
    title: 'Bí quyết bảo quản đồ nội thất gỗ bền đẹp',
    slug: 'bi-quyet-bao-quan-do-noi-that-go-ben-dep',
    excerpt: 'Chia sẻ kinh nghiệm bảo quản, vệ sinh nội thất gỗ giúp đồ dùng luôn như mới.',
    content: '',
    thumbnailUrl: '/images/blog/blog-3.jpg',
    authorName: 'Nội Thất Xinh',
    createdAt: '2024-05-10T08:00:00Z',
  },
];

// --- Testimonial mẫu ---
export const mockTestimonials = [
  {
    id: 1,
    name: 'Nguyễn Thị Mai',
    content: 'Mình rất hài lòng với bộ sofa MOCHI. Chất vải đẹp, ngồi rất êm. Giao hàng nhanh, nhân viên lắp đặt rất nhiệt tình.',
    rating: 5,
    avatarUrl: '/images/avatars/avatar-1.jpg',
  },
  {
    id: 2,
    name: 'Trần Văn Hùng',
    content: 'Giường COMET chất lượng xuất sắc. Thiết kế đẹp, chắc chắn. Rất đáng đồng tiền!',
    rating: 5,
    avatarUrl: '/images/avatars/avatar-2.jpg',
  },
  {
    id: 3,
    name: 'Lê Thị Hương',
    content: 'Tủ quần áo ASTRO rộng rãi, chứa được rất nhiều đồ. Kính cường lực sáng bóng, nhìn rất sang trọng.',
    rating: 4,
    avatarUrl: '/images/avatars/avatar-3.jpg',
  },
];

// --- Danh mục phòng ---
export const mockRoomCollections = [
  { id: 1, name: 'Phòng khách', slug: 'phong-khach', imageUrl: '/images/rooms/living-room.jpg', productCount: 45 },
  { id: 2, name: 'Phòng ngủ', slug: 'phong-ngu', imageUrl: '/images/rooms/bedroom.jpg', productCount: 38 },
  { id: 3, name: 'Phòng làm việc', slug: 'phong-lam-viec', imageUrl: '/images/rooms/office.jpg', productCount: 22 },
  { id: 4, name: 'Phòng ăn', slug: 'phong-an', imageUrl: '/images/rooms/dining.jpg', productCount: 18 },
];
